import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './styles/style.css';
import {Header} from './components/Header';
import Footer from './components/Footer';
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ben Chang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{margin: '0'}}className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
